/* eslint-disable prettier/prettier */
// * there are 58 cards total

const deck = [
  { suite: 'club', value: 3, cardID: 0 },
  { suite: 'club', value: 4, cardID: 0 },
  { suite: 'club', value: 5, cardID: 0 },
  { suite: 'club', value: 6, cardID: 0 },
  { suite: 'club', value: 7, cardID: 0 },
  { suite: 'club', value: 8, cardID: 0 },
  { suite: 'club', value: 9, cardID: 0 },
  { suite: 'club', value: 10, cardID: 0 },
  { suite: 'club', value: 'J', cardID: 0 },
  { suite: 'club', value: 'Q', cardID: 0 },
  { suite: 'club', value: 'K', cardID: 0 },
  { suite: 'heart', value: 3, cardID: 0 },
  { suite: 'heart', value: 4, cardID: 0 },
  { suite: 'heart', value: 5, cardID: 0 },
  { suite: 'heart', value: 6, cardID: 0 },
  { suite: 'heart', value: 7, cardID: 0 },
  { suite: 'heart', value: 8, cardID: 0 },
  { suite: 'heart', value: 9, cardID: 0 },
  { suite: 'heart', value: 10, cardID: 0 },
  { suite: 'heart', value: 'J', cardID: 0 },
  { suite: 'heart', value: 'Q', cardID: 0 },
  { suite: 'heart', value: 'K', cardID: 0 },
  { suite: 'spade', value: 3, cardID: 0 },
  { suite: 'spade', value: 4, cardID: 0 },
  { suite: 'spade', value: 5, cardID: 0 },
  { suite: 'spade', value: 6, cardID: 0 },
  { suite: 'spade', value: 7, cardID: 0 },
  { suite: 'spade', value: 8, cardID: 0 },
  { suite: 'spade', value: 9, cardID: 0 },
  { suite: 'spade', value: 10, cardID: 0 },
  { suite: 'spade', value: 'J', cardID: 0 },
  { suite: 'spade', value: 'Q', cardID: 0 },
  { suite: 'spade', value: 'K', cardID: 0 },
  { suite: 'star', value: 3, cardID: 0 },
  { suite: 'star', value: 4, cardID: 0 },
  { suite: 'star', value: 5, cardID: 0 },
  { suite: 'star', value: 6, cardID: 0 },
  { suite: 'star', value: 7, cardID: 0 },
  { suite: 'star', value: 8, cardID: 0 },
  { suite: 'star', value: 9, cardID: 0 },
  { suite: 'star', value: 10, cardID: 0 },
  { suite: 'star', value: 'J', cardID: 0 },
  { suite: 'star', value: 'Q', cardID: 0 },
  { suite: 'star', value: 'K', cardID: 0 },
  { suite: 'diamond', value: 3, cardID: 0 },
  { suite: 'diamond', value: 4, cardID: 0 },
  { suite: 'diamond', value: 5, cardID: 0 },
  { suite: 'diamond', value: 6, cardID: 0 },
  { suite: 'diamond', value: 7, cardID: 0 },
  { suite: 'diamond', value: 8, cardID: 0 },
  { suite: 'diamond', value: 9, cardID: 0 },
  { suite: 'diamond', value: 10, cardID: 0 },
  { suite: 'diamond', value: 'J', cardID: 0 },
  { suite: 'diamond', value: 'Q', cardID: 0 },
  { suite: 'diamond', value: 'K', cardID: 0 },
  { suite: 'joker', value: 'joker', cardID: 0 },
  { suite: 'joker', value: 'joker', cardID: 1 },
  { suite: 'joker', value: 'joker', cardID: 2 },
  { suite: 'club', value: 3, cardID: 1 },
  { suite: 'club', value: 4, cardID: 1 },
  { suite: 'club', value: 5, cardID: 1 },
  { suite: 'club', value: 6, cardID: 1 },
  { suite: 'club', value: 7, cardID: 1 },
  { suite: 'club', value: 8, cardID: 1 },
  { suite: 'club', value: 9, cardID: 1 },
  { suite: 'club', value: 10, cardID: 1 },
  { suite: 'club', value: 'J', cardID: 1 },
  { suite: 'club', value: 'Q', cardID: 1 },
  { suite: 'club', value: 'K', cardID: 1 },
  { suite: 'heart', value: 3, cardID: 1 },
  { suite: 'heart', value: 4, cardID: 1 },
  { suite: 'heart', value: 5, cardID: 1 },
  { suite: 'heart', value: 6, cardID: 1 },
  { suite: 'heart', value: 7, cardID: 1 },
  { suite: 'heart', value: 8, cardID: 1 },
  { suite: 'heart', value: 9, cardID: 1 },
  { suite: 'heart', value: 10, cardID: 1 },
  { suite: 'heart', value: 'J', cardID: 1 },
  { suite: 'heart', value: 'Q', cardID: 1 },
  { suite: 'heart', value: 'K', cardID: 1 },
  { suite: 'spade', value: 3, cardID: 1 },
  { suite: 'spade', value: 4, cardID: 1 },
  { suite: 'spade', value: 5, cardID: 1 },
  { suite: 'spade', value: 6, cardID: 1 },
  { suite: 'spade', value: 7, cardID: 1 },
  { suite: 'spade', value: 8, cardID: 1 },
  { suite: 'spade', value: 9, cardID: 1 },
  { suite: 'spade', value: 10, cardID: 1 },
  { suite: 'spade', value: 'J', cardID: 1 },
  { suite: 'spade', value: 'Q', cardID: 1 },
  { suite: 'spade', value: 'K', cardID: 1 },
  { suite: 'star', value: 3, cardID: 1 },
  { suite: 'star', value: 4, cardID: 1 },
  { suite: 'star', value: 5, cardID: 1 },
  { suite: 'star', value: 6, cardID: 1 },
  { suite: 'star', value: 7, cardID: 1 },
  { suite: 'star', value: 8, cardID: 1 },
  { suite: 'star', value: 9, cardID: 1 },
  { suite: 'star', value: 10, cardID: 1 },
  { suite: 'star', value: 'J', cardID: 1 },
  { suite: 'star', value: 'Q', cardID: 1 },
  { suite: 'star', value: 'K', cardID: 1 },
  { suite: 'diamond', value: 3, cardID: 1 },
  { suite: 'diamond', value: 4, cardID: 1 },
  { suite: 'diamond', value: 5, cardID: 1 },
  { suite: 'diamond', value: 6, cardID: 1 },
  { suite: 'diamond', value: 7, cardID: 1 },
  { suite: 'diamond', value: 8, cardID: 1 },
  { suite: 'diamond', value: 9, cardID: 1 },
  { suite: 'diamond', value: 10, cardID: 1 },
  { suite: 'diamond', value: 'J', cardID: 1 },
  { suite: 'diamond', value: 'Q', cardID: 1 },
  { suite: 'diamond', value: 'K', cardID: 1 },
  { suite: 'joker', value: 'joker', cardID: 3 },
  { suite: 'joker', value: 'joker', cardID: 4 },
  { suite: 'joker', value: 'joker', cardID: 5 },
  // { suite: 'joker', value: 'joker', cardID: 13 },
  // { suite: 'joker', value: 'joker', cardID: 14 },
  // { suite: 'joker', value: 'joker', cardID: 15 },
  // { suite: 'joker', value: 'joker', cardID: 31 },
  // { suite: 'joker', value: 'joker', cardID: 41 },
  // { suite: 'joker', value: 'joker', cardID: 51 },
  // { suite: 'joker', value: 'joker', cardID: 32 },
  // { suite: 'joker', value: 'joker', cardID: 42 },
  // { suite: 'joker', value: 'joker', cardID: 52 },
  // { suite: 'joker', value: 'joker', cardID: 321 },
  // { suite: 'joker', value: 'joker', cardID: 421 },
  // { suite: 'joker', value: 'joker', cardID: 521 },
  // { suite: 'joker', value: 'joker', cardID: 321 },
  // { suite: 'joker', value: 'joker', cardID: 421 },
  // { suite: 'joker', value: 'joker', cardID: 521 },
];

export default deck;
