/* eslint-disable prettier/prettier */
// * there are 58 cards total

const deck = [
  { suite: 'club', value: 3 },
  { suite: 'club', value: 4 },
  { suite: 'club', value: 5 },
  { suite: 'club', value: 6 },
  { suite: 'club', value: 7 },
  { suite: 'club', value: 8 },
  { suite: 'club', value: 9 },
  { suite: 'club', value: 10 },
  { suite: 'club', value: 'J' },
  { suite: 'club', value: 'Q' },
  { suite: 'club', value: 'K' },
  { suite: 'heart', value: 3 },
  { suite: 'heart', value: 4 },
  { suite: 'heart', value: 5 },
  { suite: 'heart', value: 6 },
  { suite: 'heart', value: 7 },
  { suite: 'heart', value: 8 },
  { suite: 'heart', value: 9 },
  { suite: 'heart', value: 10 },
  { suite: 'heart', value: 'J' },
  { suite: 'heart', value: 'Q' },
  { suite: 'heart', value: 'K' },
  { suite: 'spade', value: 3 },
  { suite: 'spade', value: 4 },
  { suite: 'spade', value: 5 },
  { suite: 'spade', value: 6 },
  { suite: 'spade', value: 7 },
  { suite: 'spade', value: 8 },
  { suite: 'spade', value: 9 },
  { suite: 'spade', value: 10 },
  { suite: 'spade', value: 'J' },
  { suite: 'spade', value: 'Q' },
  { suite: 'spade', value: 'K' },
  { suite: 'star', value: 3 },
  { suite: 'star', value: 4 },
  { suite: 'star', value: 5 },
  { suite: 'star', value: 6 },
  { suite: 'star', value: 7 },
  { suite: 'star', value: 8 },
  { suite: 'star', value: 9 },
  { suite: 'star', value: 10 },
  { suite: 'star', value: 'J' },
  { suite: 'star', value: 'Q' },
  { suite: 'star', value: 'K' },
  { suite: 'diamond', value: 3 },
  { suite: 'diamond', value: 4 },
  { suite: 'diamond', value: 5 },
  { suite: 'diamond', value: 6 },
  { suite: 'diamond', value: 7 },
  { suite: 'diamond', value: 8 },
  { suite: 'diamond', value: 9 },
  { suite: 'diamond', value: 10 },
  { suite: 'diamond', value: 'J' },
  { suite: 'diamond', value: 'Q' },
  { suite: 'diamond', value: 'K' },
  { suite: 'joker', value: 'joker' },
  { suite: 'joker', value: 'joker' },
  { suite: 'joker', value: 'joker' },
];

export default deck;
