import { StyleSheet } from 'react-native';
import EStyleSheet from 'react-native-extended-stylesheet';

const styles = StyleSheet.create({
  button: {
    alignContent: 'center',
    backgroundColor: 'white',
    borderColor: '#E7C721',
    borderRadius: 10,
    borderWidth: 2,
    bottom: -100,
    height: 41,
    justifyContent: 'center',
    marginRight: 10,
    marginTop: 20,
    width: 103,
  },
  buttonText: {
    textAlign: 'center',
  },
  container: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 120,
    padding: 10,
  },
  deck: {
    backgroundColor: 'purple',
    borderColor: '#E7C721',
    borderRadius: 10,
    borderWidth: 2,
    height: 116.66,
    marginRight: -83.33,
    shadowColor: 'blue',
    shadowOffset: {
      width: 10,
      height: 0.5,
    },
    shadowOpacity: 1,
    shadowRadius: 0.75,
    width: 83.33,
  },
  deckAndFaceUpCardContainer: {
    position: 'absolute',
    top: 60,
    width: '100%',
  },
  deckContainer: {
    backgroundColor: 'blue',
    borderColor: '#E7C721',
    borderRadius: 10,
    borderWidth: 2,
    height: 116.66,
    left: '22.5%',
    position: 'absolute',
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowOpacity: 1,
    shadowRadius: 0.75,
    width: 83.33,
  },
  deckContainerHighlight: {
    shadowColor: 'blue',
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowOpacity: 1,
    shadowRadius: 0.75,
  },
  faceUpCard: {
    left: '22.5%',
    paddingLeft: 120,
  },
  helpButton: {
    backgroundColor: 'white',
    color: 'white',
    right: 100,
  },
  modalContainer: {
    alignItems: 'center',
    backgroundColor: 'white',
    borderRadius: 22,
    height: '70%',
    justifyContent: 'center',
    width: '80%',
  },
  outerContainer: {
    alignContent: 'center',
    alignItems: 'center',
    // flex: 1,
    height: '100%',
  },
  playerView: {
    bottom: 0,
  },
  subHandFour: {
    backgroundColor: 'black',
    borderRadius: 15,
    bottom: 315,
    height: 130,
    opacity: 0.5,
    position: 'absolute',
    right: 10,
    width: '46%',
  },
  subHandOne: {
    backgroundColor: 'black',
    borderRadius: 15,
    bottom: 175,
    height: 130,
    left: 10,
    opacity: 0.5,
    position: 'absolute',
    width: '46%',
  },
  subHandThree: {
    backgroundColor: 'black',
    borderRadius: 15,
    bottom: 315,
    height: 130,
    left: 10,
    opacity: 0.5,
    position: 'absolute',
    width: '46%',
  },
  subHandTwo: {
    backgroundColor: 'black',
    borderRadius: 15,
    bottom: 175,
    height: 130,
    opacity: 0.5,
    position: 'absolute',
    right: 10,
    width: '46%',
  },
  text: {
    color: 'white',
    fontFamily: 'Inter_300Light',
  },
  textFaceUpCard: {
    color: 'white',
    fontFamily: 'Inter_300Light',
    marginTop: 10,
  },
});

export default styles;
